language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
android:
  components:
    - platform-tools
    - build-tools-22.0.1
    - android-22
    - sys-img-armeabi-v7a-android-22
